aergoio/aergo

config/types.go
glide.lock
glide.yaml
rpc/rpc.go

This uses a [grpc-web wrapper](https://github.com/improbable-eng/grpc-web#why) to support browsers.
For review by @kjunu as I rewrote some of his code.
grpc-web is a protocol extention over plain grpc. See https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md
Maybe we need to keep support for the "basic" GRPC protocol for the Java client? Maybe publish them on different ports? I guess @bylee needs to test this.
Companion PR: https://github.com/aergoio/herajs/pull/2

[WIP] [rpc] Wrap grpc server for grpc-web compatability

---

rpc/rpc.go

I found that java gRPC client is not compatible with current matcher.
According to [cmux repository](https://github.com/soheilhy/cmux), use MatchWithWriter when using grpc java client.
But we have to check MatchWithWriter version is compatible with [herajs](https://github.com/aergoio/herajs). Maybe @graup have to test it.

[RPC] Matching http2 with writer for java-grpc compatibility

---

account/accountservice.go
account/accountservice_test.go
account/key/address.go
account/key/sign.go
account/key/store.go
blockchain/chainhandle.go
cmd/aergocli/cmd/accounts.go
cmd/aergocli/cmd/contract.go
cmd/aergocli/cmd/getstate.go
cmd/aergocli/cmd/signtx.go
cmd/aergocli/cmd/vote.go
contract/vm.go
contract/vm_test.go
glide.lock
glide.yaml
types/account.go
types/receipt.go

I refactored the address encoding/decoding into the `types` package (`EncodeAddress`, `DecodeAddress`). Please use these instead of the direct calls to base58! The new scheme uses base58check.
I also adjusted the account address generation to use the last 20 bytes of a hash of the pubkey, like Ethereum does.
I changed almost all occurrences of `base58` in the codebase to use the new `EncodeAddress` function, but it is possible I missed something.

[accounts] new address format

---

cmd/aergosvr/aergosvr.go
config/config.go
config/types.go
mempool/mempool.go

Needed for testing. It's too complicated to generate and use a genesis block and account for testing.

[cfg] testmode to skip account balance validation

---

cmd/aergocli/cmd/accounts.go

When both --password and --newpassword target is empty, cmd guide to type password. But that password isn't used as an new password.

[CLI] Fix when importing account

---

account/key/store.go
cmd/aergocli/cmd/keygen.go

There's currently no easy way to just generate a private key and address offline (without a server and internet connection). Herajs and Herajs can do that, of course, but if someone just want to quickly make a new account, that's not that easy to use.
I figured that aergocli `keygen` does pretty much exactly that, but it didn't export the new key in the format used by other tools. So I added the option `--json --pasword test` so that the new key's address and encrypted key are exported.
Usage example:
```shell
./bin/aergocli keygen anotherKey2 --json --password test
{
"address": "AmLa1Ux6wpd3xcpwTtXCbCXMrNpQiFpozvYTYT5kd9zKh3fCMaNr",
"pubkey": "CAISIQKNjr90xIDEkZu/AYZXOCIvIr5GoeokgQk7R6/B1fAj5Q==",
"privkey": "MRGtvN2BBiKvAhyaJi2QEbTAUNzN59UvZZcJXtTjJyZ5j44X4iwG3o3UeWKVMNXjzvrfh7MXHGkds6", …
```

[cli] keygen --json option to export address and encrypted privkey

---

p2p/mocks/mock_networktransport.go
p2p/networktransport.go
p2p/peermanager.go
p2p/pmap/mapservice.go
p2p/pmap/mapservice_test.go

It will solve occational panic while initializing p2p and pmap actors.

[P2P] Fix occational panic in initializing map actor

---

mempool/mempool.go

When undefined name is in recipient, mempool have to check existence of an address corresponding to name.

Make error when not defined recipient name

---

.travis.yml

This configuration uses Travis to automatically builds linux and macOS binaries and deploy them to the Github releases page whenever a new tag is added.

Travis build and deploy releases

---

chain/blockvalidator.go
chain/chainhandle.go
chain/signVerifier.go
chain/signverifier_test.go
contract/name/execute_test.go
contract/name/name.go
contract/name/name_test.go
mempool/mempool.go
types/blockchain.go

To validate transactions in parallel in a block, transactions that create or update names are effective after they are mined and entered the block. Therefore, if any of the past blocks contain transactions that use the changed name after you rename them, the blocks become invalid and break their backward compatibility.
블록 안에 트랜잭션을 병렬적으로 검증하기 위해서, 이름을 만들거나 변경하는 트랜잭션은 채굴되어 블록에 들어간 이후 부터 효력이 발휘됩니다. 때문에 과거 블록 중에 이름을 변경한 후에 변경된 이름을 이용하는 트랜잭션이 포함된 것이 있다면, 그 블록은 유효하지 않은 블록이 되어 하위 호환성이 깨집니다.

[name] Refactor code for varification

---

p2p/internalconst.go
p2p/libp2putil.go
p2p/libp2putil_test.go
p2p/p2p.go

- Show more accurate error message when specified pk file does not
exist or is not a valid private key file.
- Make and save to default key file when no pk file is specified
and reuse after reboot, to make continuity.
- Generated file location: ${USER_HOME}/.aergo/aergo-peer.key

[P2P] Change behavior of initializing private key

---

chain/chaindb.go
chain/chainservice_test.go
chain/reorg.go
consensus/consensus.go
consensus/impl/dpos/lib.go
consensus/impl/dpos/status.go
consensus/impl/raft/blockfactory.go
consensus/impl/sbp/sbp.go

1. fix bug where old tx mapping could not committed when swapping tx mapping.
old txs has saved in transaction but not commited if tx count < 10000.
but when rpc is called, tx mapping info is dropped if block of tx isn't included in chain 
2. refactoring - apply bulk transaction when swapping chain info during reorg

[CHAIN] fix reorg bug & refactoring

---

cmd/brick/example/hello.brick

hello.brick was failing with:
ERR execution fail error="not enough balance" cmd=deploy module=brick
example/hello.brick:8 deploy bj 0 helloctr `./example/hello.lua`
so increase the balance provided.

[brick] Ensure hello.brick has enough account balance to run

---

cmd/aergoluac/main.go

Always return non-zero exit code on error for consistency.  This ensures that if `aergoluac` is called from within shell scripts / Makefiles etc., errors can be properly detected and handled.
Returning the error from the `cobra.Command` closure automatically causes it to be output to `STDERR`, so we don't need to print it ourselves.

Ensure aergoluac has a non-zero exit code on error

---

cmd/aergocli/cmd/accounts.go
cmd/aergocli/cmd/accounts_test.go
cmd/aergocli/cmd/config.go
cmd/aergocli/cmd/contract.go
cmd/aergocli/cmd/name.go
cmd/aergocli/cmd/root.go
cmd/aergocli/cmd/sendtx.go
cmd/aergocli/cmd/sendtx_test.go
cmd/aergocli/cmd/signtx.go
cmd/aergocli/cmd/signtx_test.go
cmd/aergocli/cmd/stake.go
cmd/aergocli/cmd/vote.go

This allows local keystore to be used with all account commands (incl sendtx etc).
BREAKING CHANGE
- The new default behavior is to use a local keystore at `$HOME/.aergo`
- You can change the keystore directory by supplying `--keystore /path/to/keystore/`
- To restore the old behavior (using a server provided keystore), pass `--node-keystore`
Remote keystore functionality will be removed in future versions. The reason is that this is prone to unsafe misuse - if used with a publicly accessible node, this can expose user information to the public.

support keystore in aergocli

---

cmd/aergocli/cmd/getblock.go

- Use `RunE` and return errors from handler
- Better error messages with context
- Split the two modes into separate functions
- Remove unreachable return statement after infinite loop

[cli] refactor getblock, improve error handling

---

cmd/aergocli/cmd/contract.go
cmd/aergocli/cmd/sendtx.go
types/blockchain.go

- Improved Usage and Error messages
- Cleaned up code
New usage messages:
```
$ aergocli contract deploy
Error: requires exactly 1, 2, 3 or 4 args but received 0
Usage:
aergocli contract deploy [flags] --payload 'payload string' <creatorAddress> [args]
aergocli contract deploy [flags] <creatorAddress> <bcfile> <abifile> [args]
You can pass constructor arguments by passing a JSON string as the optional final parameter, e.g. "[1, 2, 3]".
Flags:
--amount string     amount of token to send with deployment, in aer (default "0")
-h, --help              help for deploy
--password string   password (optional, will be asked on the terminal if not given)
--payload string    result of compiling a contract
-r, --redeploy string   redeploy the contract
```
```
$ aergocli contract call
Error: requires …
```

[cli] Clarify command line usage. Fixes #121

---

cmd/brick/brick.go
cmd/brick/exec/batch.go

Always return non-zero exit code on error for consistency.  This ensures that if brick is called from within shell scripts / Makefiles etc., errors can be properly detected and handled.

Ensure brick has a non-zero exit code on error

---

account/key/store.go
cmd/aergocli/cmd/accounts.go
cmd/aergocli/cmd/accounts_test.go

When to import an account, if the same account exists already, `aergocli` shows only `already exist` message.
However, if `aergocli` shows the error with the address, it would be helpful to make an automated script or else.

add to show address even if fail to import account

---

contract/vm.go

Fixes #113 
This changes the error messages in Lua from this:
```
"[string \"5a54b761f0908e98698db696a8623c910875a54b761f0908e98698db696a8623c9\"]:2: attempt to concatenate local 'name' (a nil value)"
```
To this:
```
"Amhfxh8VUPEpUGHuxyQCLn7shbyJeiQ2jujwV3i21g6b6JhDSoxQ:2: attempt to concatenate local 'name' (a nil value)"
```

Use the contract address on error messages

---

state/contract.go

Copies of the same smart contract should be stored in a single place, to reduce the space used.
Some of new contracts can reach thousands of instances, all of them with exactly the same code

Store contract code just once

---

contract/vm.go

JSON objects that are sent as argument in a transaction are processed using a mapping in Go, that do not have ordering. 
This change process the mapping in a deterministic way by sorting the keys
It appears that this does not require a check for hardfork because the original behavior itself leads to different result on separate nodes
A sync test is required

Makes parsing JSON object deterministic

---

cmd/brick/context/util.go
cmd/brick/exec/batch.go

These changes add support for multi-line commands on batch files
The commands can be break into many lines when inside back-sticks (`)
Example:
```
call ac1 0 contract set_values `[
123,
["first","second","last"],
["and another one", true]
]` `"TEST"`
```

brick: multi-line commands on batch mode

---

contract/vm_dummy.go

I am not sure if there is a reason for the `bc` argument to be null in this case.
But this change fixes the problem.
Fixes #138 
Fixes #151

brick: fix segmentation fault

---

contract/vm_test.go

- skip tests in vm_test.go on non amd64 architecture since those tests are archtecture dependent.

Tune unit test in vm_test.go

---

cmd/aergocli/cmd/contract.go

Allow `aergocli` to accept contract code encoded in hex format.
This is used to deploy a copy of an existing contract to another chain, or even the same. Also used for test purposes, when deployed locally.
The data in hex format is copied from aergoscan view of the transaction that deployed the contract.
With this change, the payload given to `aergocli` on `contract deploy` can be either in hex format or the format generated by `aergoluac --payload`

aergocli: deploy contract in hex format

---

contract/contract.go

this was recently introduced on [this commit](https://github.com/aergoio/aergo/commit/94cc003b89b0ef0d521708bebab7774d50fd7617)

fix bug on preload

---

contract/vm.h

add stdint.h in vm.h.
window machine cant build aergo because it use mingw compiler.
( mingw don`t know size of uint8_t or uint16_t without import stdint. )
unlikely happens.

add stdint in vm.h

---

tests/common.sh
tests/test-gas-bf.sh
tests/test-gas-deploy.sh
tests/test-gas-op.sh
tests/test-gas-per-function-v2.sh
tests/test-gas-per-function-v3.sh
tests/test-gas-verify-proof.sh
tests/test-max-call-depth.sh

`aergocli` will work differently if deploying for <= V3 or >= V4
These new functions prepare the integration tests for new deploy method on #266
Although this is focused on changes to be applied only on V4, the changes here are backwards compatible and it is useful to merge them before so other work made on integration tests can use these new functions

new functions for integration tests

---

chain/chainhandle_test.go
chain/chainservice.go
contract/name/execute.go
contract/name/name.go
contract/name/name_test.go
contract/system/staking.go
contract/system/vote.go
contract/system/vote_test.go
contract/vm_dummy/vm_dummy.go
mempool/mempool.go

remove system.InitGovernance ( it is not used )
tidy codes about make event args

small refactoring about names, staking, votings

---

consensus/consensus.go
consensus/impl/raftv2/blockfactory.go
consensus/impl/sbp/sbp.go

It fix bug that the blocks are generated too much in raft consensus. 
It preserve behavior of v2.4.7 at best effort.

fix wrong block generation inverval in raft

---

contract/vm_direct/vm_direct.go

This file is used by [tx-replay](https://github.com/aergoio/tx-replay) to execute transactions directly on the VM without using the chain, consensus and mempool packages

add vm_direct

---

contract/contract_module.c
contract/vm.c
contract/vm.go
contract/vm_dummy/vm_dummy_test.go

This makes the `pcall` and `xpcall` rollback the contract state (state variables, nonce, balance, sql db) when the called function fails
The PR is built on top of #199 and it is made to be merged into it first, if approved
It is made into a separate PR in order to discuss if this is a bug-fix, what is the expected behavior of these functions, and if backwards compatibility is required

rollback contract state on failed pcall

---

consensus/impl/dpos/blockfactory_test.go

This test was sometimes failed by timing issue, such like in heavy load in host machine of container.

Fix occasional failure of unit test

---

rpc/rpc.go

As a guess, it seems that originally the prev code was assumed that only grpcweb was supported, so if an http request other than grpc came, it could be an incorrect request or an impure intention, so it recorded logs at INFO level.
However, many other requests are coming in, so there are quite a lot of logs recorded on the testnet nodes, but there is no context in that log messages, so a lot of meaningless messages are piling up.
This commit is not a solution of the problem. The code has been modified to leave more detailed logs for analysis, and a commit that fixes the real problem will be recreated using the logs produced by this commit.

Change log message of unidentified http request for investigation

---

pkg/trie/trie_tools.go
state/statedb/dump.go
state/statedb/dump_test.go
state/statedb/statedb.go

support dump for account, contract, contract storage in state trie
no. it is for debug and test only.

add state dump

---

contract/vm.go
contract/vm_callback.go
contract/vm_state.go
state/account.go
state/statedb/contract.go
state/statedb/contract_test.go
types/blockchain.pb.go

Save the source code of the deployed contract (both via transaction and via `contract.deploy()`) on the contract state, starting on hardfork V4
The previous method for V4 was to just compile the source code from the transaction and store only the bytecode
Now both bytecode and source code would be stored
This can be useful in the future if we want to use a Lua interpreter instead of LuaJIT (for some contracts)

save contract source code

---

cmd/aergocli/cmd/getpeers.go

- Added flag options for `--detail=-2`
- new option will show peers with fixed width size
- it also can show alias name of node.

aergocli: added option to getpeer command

---

account/key/crypto/v1strategy.go

Since err != nil has been judged before, nil is returned directly here, which is more obvious, readable and less error-prone.

Use a more direct and less error-prone return value

---

config/config_test.go

`TempDir()` is a method introduced in Go 1.15 for `testing.T`. It automatically creates a temporary directory and cleans it up after the test is complete, eliminating the hassle of manually handling errors and cleanup.  More detail about TempDir  https://pkg.go.dev/testing#B.TempDir

refactor: use t.TempDir() instead of os.MkdirTemp

---

cmd/aergocli/cmd/event.go

This PR adds 2 limits to event stream on `aergocli`:
* Limit of events to receive
* Limit of time to wait (timeout)

aergocli: add limits to event stream

---

CMakeLists.txt
chain/chainservice.go

when `forceresetheight` is used, `aergosvr` will exit just after removing new blocks from the db

attempt to fix force reset height

---

CMakeLists.txt
cmd/aergocli/cmd/contract.go
cmd/brick/brick.go
cmd/brick/exec/deployContract.go
cmd/brick/exec/pack.go
cmd/brick/pack/pack.go
tests/run_tests.sh
tests/test-import-1.lua
tests/test-import-2.lua
tests/test-import-expected-bundle.lua
tests/test.brick

Contracts deployed with `brick` and `aergocli` now support the `import` statement in the following format:
```js
import 'file.lua'
import "path/to/another/file.lua"
import "https://raw.githubusercontent.com/aergoio/aergo-contract-ex/refs/heads/master/contracts/typecheck/typecheck.lua"
...
```
So there is no need to use `ship`

deploy: add support for import statement on aergocli and brick

---

cmd/aergocli/cmd/contract.go

print the result of `aergocli contract statequery` in JSON format
also adds a new `--fullproof` command-line option, that defaults to `false`
so the `contract statequery` command will by default print only the value
if `--fullproof true` is added, it will print the full proof

aergocli: print query contract state result as JSON
