- rpc/grpcserver.go
Input can only be 32 bytes (hash) or 8 byte (uint64). Anything else should throw an error.
> [rpc] Fix GetBlock input handling

- p2p/actorwork.go
- p2p/subprotocolblock.go
- rpc/grpcserver.go
- types/blockchain.go
I changed codes in p2p, rpc and types. 
@qcollapse  Check file types/blockchain.go, please.
> [P2P][RPC] Follow up new semantic of getting block hash

- chain/chainhandle.go
It's need to improve for performance.
> [chain] Verify named account tx when chain execute

- cmd/aergocli/cmd/name.go
- contract/name/execute.go
- contract/name/name.go
- contract/name/name_test.go
please merge it before 0.10 tagging
> [name] Takes 1aergo to update name. Just like creating

- contract/system/staking.go
- contract/system/vote.go
- contract/system/vote_test.go
> [staking,voting] Change encoder to protobuf when save in trie

- internal/enc/bstr.go
- internal/enc/bstr_test.go
> [MISC] Clarify documentation

- rpc/grpcserver.go
I think 'ListBlockHeaders' and 'ListBlockMetadata' should make an error on invalid hash or height
> [RPC] Make error on getBlockHeaders when invalid height or hash

- scripts/docker-build.sh
Ported and improved a script from the old aergo-docker repo
> [scripts] add manual docker build script

- types/transaction.go
- types/transaction_test.go
This code need to reset or rollback testnet
> [aergo.name] Bugfix, add missing error handling

- consensus/consensus.go
- consensus/impl/dpos/dpos.go
- consensus/impl/impl.go
- contract/contract.go
- contract/name/execute.go
- contract/vm.go
- contract/vm_callback.go
- state/statedb.go
- types/transaction.go
Read name price from the stateDB
> [aergo.name] Fix validation for name price

- cmd/aergocli/cmd/name.go
Added `updateCmd.Flags().StringVar(&pw, "password", "", "password")` and some text improvements
> [cli] add option to pass password to name update

- mempool/mempool.go
* mempool 에서 현재 블록 높이가 아니라 다음 블록 높이 기준으로 TX 수용 검사
* system TX 도 다음 블록 높이와 다음 버젼으로 validation 검사
https://trello.com/c/Zm0LhqcF
> [mempool] Use next chainid hash to verify tx

- rpc/rpc.go
- add more detailed information to log
> [RPC] Add log field

- consensus/impl/raftv2/raftlogger.go
- raftlogger now shows stacktrace of caller, previously showed
raftlogger code itself.
> Improve raft logging message

- state/statedb.go
> Fix internal error on testmode

- cmd/brick/context/symbol.go
- cmd/brick/exec/timestamp.go
- contract/vm_dummy.go
> brick: timestamp command

- .github/workflows/build_and_test.yml
- .github/workflows/default_unittest.yml
- .github/workflows/short_unittest.yml
- mempool/mempool_test.go
- syncer/arglog.toml
- syncer/syncerservice_test.go
- Any push of any branches will trigger short unit tests.
- User can trigger normal unit tests on demand.
- Also some long running unit tests will be skipped in short unit tests
> Add github actions for unit tests

- cmd/aergocli/cmd/contract.go
- contract/vm_test.go
- tests/run_tests.sh
- tests/test-max-call-depth-1.lua
- tests/test-max-call-depth-2.lua
- tests/test-max-call-depth-3.lua
- tests/test-max-call-depth.sh
This commit has unit tests and integration tests (aergosvr + aergocli) for MaxCallDepth
> test MaxCallDepth

- Docker/Dockerfile.builder
install necessary library ( like patch )
> add build-essential when docker build

- cmd/brick/brick.go
- tests/basic.lua
- tests/run_tests.sh
- tests/test-brick.sh
- tests/test.brick
Fix error "redefined flag: v" on `brick`
> brick: fix redefined flag

- README.md
> Remove disconnected badge

- chain/chainhandle.go
- cmd/aergocli/cmd/event.go
- consensus/chain/tx.go
- contract/contract.go
- contract/name/execute.go
- contract/vm.go
- contract/vm_callback.go
- contract/vm_dummy/vm_dummy.go
And also rename some functions and variables to more clear names
> add comments to code

- tests/common.sh
- tests/config.toml
- tests/run_tests.sh
- tests/test-gas-bf.sh
- tests/test-gas-deploy.sh
- tests/test-gas-op.sh
- tests/test-gas-verify-proof.sh
- tests/test-max-call-depth.sh
This is a work-in-progress
New test cases can be added to the branch of this PR
It is possible to create many commits and send many at once in a single push, to decrease the number of CI workflow runs
> Add new integration tests

- contract/vm_dummy/vm_dummy.go
- contract/vm_dummy/vm_dummy_dbg.go
- contract/vm_dummy/vm_dummy_release.go
this is to apply some consistency with tx element names:
sender, recipient, amount, payload
> vm_dummy: rename variables

- chain/chaindb.go
- chain/chaindbForRaft.go
- chain/chainservice.go
- chain/common.go
- consensus/impl/dpos/bp/cluster.go
- consensus/impl/dpos/lib.go
- consensus/impl/dpos/lib_test.go
- consensus/impl/dpos/status.go
- consensus/impl/raftv2/cluster.go
- consensus/impl/raftv2/config.go
- consensus/impl/raftv2/raftserver.go
- consensus/impl/raftv2/snapshot.go
- consensus/impl/raftv2/waldb.go
- consensus/raftCommon.go
print cause and explaination when an panic occurs.
not at all. it is change only log message.
> replace panic to logger.Panic

- cmd/aergoluac/util/compile.c
- contract/lstate_factory.go
- contract/vm.c
- contract/vm.go
- contract/vm.h
- contract/vm_dummy/vm_dummy.go
- contract/vm_dummy/vm_dummy_test.go
- tests/test-gas-bf.sh
The mutex on Lua states appears to be unnecessary
The problem of difference in gas was fixed on hardfork 3 on #180 
A sync test will be run on available networks
> remove mutex on Lua states

- chain/chainhandle.go
( rollback to use previous block )
> fix - update vpr when execute failed

- contract/contract_module.c
- contract/system_module.h
- contract/vm.go
- contract/vm_callback.go
* move `setRemainingGas` to another file
* use variable name `ctx` for `vmContext`, for concistency
> small changes on contract package

- contract/bignum_module.c
- contract/db_module.c
- contract/state_module.c
- contract/vm.c
It was lacking to add `lua_pop()` on 2 places
> pop module from stack after luaL_register

- account/accountservice.go
- chain/chainservice.go
- chain/governance.go
- chain/signVerifier.go
- consensus/impl/dpos/dpos.go
- contract/enterprise/config_test.go
- contract/name/execute.go
- contract/name/execute_test.go
- contract/name/name_test.go
- contract/system/execute_test.go
- contract/system/staking_test.go
- contract/system/vote_test.go
- contract/system/vprt_test.go
- contract/vm_dummy/vm_dummy.go
- mempool/mempool.go
- state/chainstatedb.go
- state/contract.go
OpenContractStateAccount(XXX) to GetXXXAccountState()
not at all.
> small refactoring about contract state

- contract/vm_dummy/vm_dummy_pub_test.go
- contract/vm_dummy/vm_dummy_test.go
This is to remove the next line which repeats the name of the file
> tests: make readLuaCode() a helper function

- contract/vm_dummy/vm_dummy_test.go
small change for formatting vm_dummy_test code
no
> formatting code

- cmd/aergosvr/aergosvr.go
- cmd/polaris/polaris.go
- cmd/polaris/polaris_test.go
- config/config.go
- config/types.go
remove pprof to prevent unintended exposure about profile path.
no.
> remove pprof

- .github/workflows/full_test.yml
- .github/workflows/manual_test.yml
- .github/workflows/short_test.yml
- go.mod
- go.sum
- actions/setup-go will not work without quote of go version
- repository of indirectly dependent library was changed.
> Small improvement of automation

- chain/chainservice.go
- state/statedb/statedb.go
check legacy trie key format ( related with #200 )
no.
> check legacy trie key

- contract/vm_callback.go
sync test in local chain was pass now. (by @kslee8282 )
> handle timeout in delegatecall

- cmd/aergocli/cmd/event.go
- cmd/aergocli/cmd/receipt.go
- rpc/web3/v1.go
- types/jsonrpc/receipt.go
- types/receipt.go
rollback some json format for cli / web3 ( receipt, event )
no.
> rollback receipt and event format

- cmd/aergocli/cmd/signtx.go
- Added the features for signtx and verifytx to read transactions from a file.
> Improved usability of aergocli

- Docker/Dockerfile.builder
- Docker/Dockerfile.local
- Docker/build-local.sh
Instead of using `git clone` and retrieving from repository
It can be used to build when the local folder has changes that were not committed, for testing purposes
> build docker image from local folder

- CMakeLists.txt
- Makefile
- tools/mpdumpdiag/main.go
- types/jsonrpc/encoding.go
- types/jsonrpc/encoding_test.go
- types/jsonrpc/tx.go
- Add flag to change format of payload.
> Improve mpdumpdiag

- config/hardfork_gen.go
I cancelled the test because this change is minimal
> apply block heights for hardfork 4

- tests/common.sh
fix sporadic failure by making all RPC calls be sent to the same node
> fix integration tests

- Docker/Dockerfile.builder
- Docker/Dockerfile.local
Fix the warning:
```
FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)
```
> fix warning on dockerfiles

- types/blockchain.go
- types/state.go
make function comment match function name
> chore: make function comment match function name

- chain/common.go
- chain/signVerifier.go
- mempool/mempool.go
- rpc/txputter.go
* add IsMainNet() function
* rename some functions
* add comments to code
> minor changes

- .github/workflows/full_test.yml
- tests/common.sh
- tests/run_tests.sh
use `aergo/node:2.6.1` instead of `aergo/node:2.6.0` on the integration tests
> fix integration test with previous version

- state/statedb/dump.go
- state/statedb/dump_test.go
- new dump function for flexible use.
> Refactoring dump account features

- Makefile
- cmd/aergoluac/luac/compile.c
- contract/vm.c
make the packages available when built in debug mode
this is useful for `brick`, to run unit tests and functional tests
> fix build in debug mode

- rpc/grpcserver.go
- rpc/grpcserver_test.go
This fix can sovle some crashes on certain situations.
> Improved validation of input argument

- config/types.go
- p2p/p2pcommon/peermanager.go
- p2p/peermanager.go
- p2p/remotepeer.go
This PR will loosen sync failure on certain situations.
> Fix sync fails on speicfic situation

- config/types.go
- p2p/p2pcommon/peermanager.go
- p2p/peermanager.go
- p2p/remotepeer.go
- rpc/grpcserver.go
- rpc/grpcserver_test.go
> Release 2.8.1

- contract/vm_dummy/test_files/all_types.lua
- tests/run_tests.sh
- tests/test-aergocli.sh
This test will probably only pass after the 2.8.2 release is merged
> test RPC with aergocli
